### PR TITLE
Avoiding external connections to Google fonts.

### PR DESCRIPTION
**Pull request by sergiotarxz**
In missconfigured servers this can lead to Google tracking the users
navigation, not good so I thinked hosting the fonts locally could be a
better option.

This is a plain copy of the opensans Google fonts css downloaded 
using Firefox.

Issue #8

### CODE REVIEW

**Comment by clickwork-git** [comment]
There is an ongoing discussion about this. And there are pros and cons.

Google for example says that it does not store personal data. Furthermore fonts are loaded often from the cache. This means in this cases is no connection to a Goggle server and the loading is normally faster than the one of a font stored on a server.

Fonts are a sort of software and often updated. Therefore it makes sense loading it from an external source.

Till now there is no law suit about this case that prohibits the use of fonts.googleapis.com.

**Comment by clickwork-git** [comment]
If you store fonts on a server, you have to store and define a whole package of fonts not only wof2.

See for example:

https://github.com/bludit-themes/log/blob/master/assets/css/bludit.css

and

https://github.com/bludit-themes/log/tree/master/assets/webfonts/open-sans

**Comment by sergiotarxz** [comment]
Ok, I will take a look I am mostly worried about servers leaking the referrer header, I would not trust Google for this, but it is not ultimately my decision. :)

**Comment by sergiotarxz** [comment]
I will close this pull request, a better solution to avoid external resources will be seek following other way, I will go meanwhile to other issues.

**Pull request closed without merging**
